### ISSUE TITLE
No creation date available

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#100]
On a file's detail page, the creation date is always empty (01.01.0001). I think this is due to NC not delivering values for `creationdate`.

Therefore, this field should be removed from the file's detail page.

**Comment by DecaTec** [comment]
Any thoughts on this?
Otherwise, I'm going to remove the creation date from the file details view.

**Comment by SunboX** [comment]
Would be better to hide it, if it's "empty". Maybe this will change in a future NC release, so it will work again without a needed change.

**Comment by DecaTec** [comment]
Solved by https://github.com/nextcloud/windows-universal/pull/124

The creation date is hidden when it's `DateTime.MinValue`.
