### ISSUE TITLE
When sorting from A to Z, the sort is wrong / mixed

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#102]
Difficult to explain, please see the attached screen shot.

![wp_ss_20170420_0002](https://cloud.githubusercontent.com/assets/83344/25250775/47960628-2617-11e7-8c2b-a93f76a620e6.png)

**Comment by DecaTec** [comment]
Also when sorting for size, the headers get cropped.
Will have a look at it at the weekend.

**Comment by DecaTec** [comment]
@SunboX How did you achieve this? I've done some testing, but the sorting is correct all the time...I think I'm missing a step to reproduce the problem.

**Comment by DecaTec** [comment]
The "cropped when sorting for size" is resolved by https://github.com/nextcloud/windows-universal/pull/106

**Comment by SunboX** [comment]
Good questing, I have to see if I can reproduce it.

**Comment by SunboX** [comment]
I can reproduce it, just by sorting alphabetically. But I can not give you access to my private nextcloud. :/ If I sort from Z to A, it looks like this:

![wp_ss_20170422_0007](https://cloud.githubusercontent.com/assets/83344/25307909/04d8167a-27aa-11e7-9801-16aeef1e8b1e.png)

**Comment by SunboX** [comment]
If I get some time, I will debug it.

**Comment by TheScientist** [comment]
I think it's pretty simple. Sorting is case sensitive

**Comment by DecaTec** [comment]
You're right. Can reproduce it now. 
Will fix asap.

**Comment by DecaTec** [comment]
Resolved by https://github.com/nextcloud/windows-universal/pull/122

**Comment by SunboX** [comment]
great, thx a lot! 😸
