### ISSUE TITLE
"PIN um zu beginnen"

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#104]
"Pin to start": The German translation is wrong ("PIN um zu beginnen", should be "An Start anheften").

@SunboX The translation is done by transifex. When I try to follow the link in the project's main page, I get a 403 error. Am I missing something?

**Comment by SunboX** [comment]
You are right, I swear the link worked at the time I changed it. I will take a look at it.

**Comment by SunboX** [comment]
Ok, got it. The link is ok, but as the 403-error page mentiones:

> You may need to login to your account first.

So, to chenge the strings you need a transifex account and you need to be logged in. I will add a note to the reade file.

**Comment by SunboX** [comment]
And I will translate the string. ;)

**Comment by DecaTec** [comment]
Got it, was my fault that it was not working.

I've changed the strings (there are two) for German (de).
I cannot change one string for German (de_DE) as the string already got reviewed and is still wrong. 

How can this be solved?

**Comment by SunboX** [comment]
@MorrisJobke 

There's a wrong translation in the de_DE language file. It's already reviewed and neighter @DecaTec nor me is able to modify this string.

@rakekniven changed it just now, but is there a way to give us (@DecaTec & @SunboX) the rights to change it? (in future)

**Comment by rakekniven** [comment]
Would you like to be moderators for german languages? Otherwise you will not be able to change already reviewed strings.

**Comment by MorrisJobke** [comment]
> @rakekniven changed it just now, but is there a way to give us (@DecaTec & @SunboX) the right to change it? (in future)

I only can make you reviewers for the whole german team (because we only have a team for all project files). But this should be no problem.

**Comment by MorrisJobke** [comment]
@DecaTec Are you fine with this too?

**Comment by SunboX** [comment]
Thanks a lot for the moderator status! :smile:

@rakekniven You are right about the issue. So I did the right thing. :smirk: So everyone knows the context about the change.
But the moderator state is nice, if we have to change something quickly. And maybe, I will moderate the windows-universal file in future. If the time allows it...

**Comment by DecaTec** [comment]
> @DecaTec Are you fine with this too?
Yes, if we can react to wrong translations a little more quickly then.

**Comment by MorrisJobke** [comment]
You both are now reviewers for de and de_DE

**Comment by DecaTec** [comment]
@MorrisJobke Thanks a lot!

The issue is closed then as the transöated strings were changed.
