### ISSUE TITLE
Manual synchronization issues

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#108]
Just as a reminder as the PR got merged: 

- [x] I would suggest that in the top (hamburger) menu, the sync item shouldn't be called "Synchronization Conflicts" because it then looks as there are always some conflicts. I would rather suggest calling it "Synchronisation Status".
- [x] That being said, it would be great to have an additional tab ("sync history") showing the last sync activities (when was the last sync, which files have been synced, etc.). This way, it's more transparent to the user what's going on.
- [x] I cannot sync the root folder ("/"), but only subfolders of it. Not sure how to handle it. Maybe there should be a sync button ("sync this folder") on the command bar (next to "sort" and "+").
- [x] I think you have the info about which folders are synchronized because there's a menu entry "Stop Synchronizing". Maybe a good idea to mark synced folders with a special icon so that the user can see at a glance which folders are being synced. This may come in handy when we will support auto sync one day.
- [x] When there is an error during sync, the error message is very generic ("Error while uploading File to nextcloud"). I don't want the user to stumble upon technical messages, but from my point of view, little more details would be great here.
- [x] When looking at the "Sync Conflicts" on mobile (Lumia 950), it's not obvious that there is an additional entry in the hub menu and that you have to swipe to the left. Maybe this can be handled by renaming the menu entries to shorter terms ("Status", "Conflicts", "Errors").
- [x] When calling the "Synchronization Conflicts" page, there seems to be a border around the content. Even more present on mobile.
- [x] The headers of the pivot control should be below the "hamburger menu bar". This should look a little cleaner and we can minimize the margin between the pivot header items

**Comment by DecaTec** [comment]
Some improvements: https://github.com/nextcloud/windows-universal/pull/112

**Comment by DecaTec** [comment]
Added

>The headers of the pivot control should be below the "hamburger menu bar". This should look a little cleaner and we can minimize the margin between the pivot header items

**Comment by DecaTec** [comment]
Current folder can now be synced: https://github.com/nextcloud/windows-universal/pull/138

To do: When a folder is synced, the (secondary) command on the app bar gets invisible but the menu of the secondary commands is not redrawn, so it shows an empty menu entry.

**Comment by DecaTec** [comment]
I couldn't find a way to set the secondary command's visibility to `Collapsed` without the secondary menu showing an empty entry. For now, the menu entry simply gets disabled: https://github.com/nextcloud/windows-universal/pull/139

**Comment by SunboX** [comment]
> When there is an error during sync, the error message is very generic ("Error while uploading File to nextcloud"). I don't want the user to stumble upon technical messages, but from my point of view, little more details would be great here.

I've two problems with that. First one in code `sid.Error = "Error while uploading File to nextcloud.";`, strings that will be shown to the user should always be translated!
Second, a more clear exception should already be shown to the user, because of: https://github.com/nextcloud/windows-universal/blob/master/NextcloudApp/Services/SyncService.cs#L589
But by now, the exception is shown as dialog to the user. This should be changed, so the exception is stored as sync conflict message.

**Comment by DecaTec** [comment]
OK, the strings are now loaded from resources: see #176 

I don't know if we can show a more clear error message to the user. In the `SyncService`, there are many general catch blocks:
````cs
catch (Exception e)
{...}
````

Without further investigation, it's hard to guess what went wrong.

@TheScientist: Maybe you can take a look at it and refine the exception handling and the error presentation to the user a bit.
