### ISSUE TITLE
Settings: Light/dark/system theme

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#119]
Let the user choose the app's theme in the settings: Light/dark/system

**Comment by SunboX** [comment]
This is also related to issue comment https://github.com/nextcloud/windows-universal/issues/18#issuecomment-262774583

**Comment by DecaTec** [comment]
https://github.com/nextcloud/windows-universal/pull/148

Theme can now be switched, but the app needs to be restarted for the settings to take effect.
This settings is saved in the roaming settings of the app.

It's a little more complex to switch themes during runtime. http://stackoverflow.com/questions/34554871/changing-theme-in-windows-10-uwp-app-programmatically

I don't know if it's worth the effort. What do you think?

**Comment by SunboX** [comment]
I've changed it, because setting it in the App's constructor crashed the share pane view. Now the theming of the message boxes and the kayboard won't change. But I think this is a minor issue. I will try one more thing, don't know if it works.

Also, the app must not be restarted now.

**Comment by SunboX** [comment]
I found a better way to dynamicall ychange the theme: https://liftcodeplay.com/2015/08/24/themeresource-dark-and-light-themes-in-windows-10/

I will implement this later.
