### ISSUE TITLE
Implement the function to pin folders and files to start screen

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#13]

**Comment by altima** [comment]
I will add a Tile service for adding, updating and removing tiles for folder's on the homescreen (and the start menu ok tablet/desktop).

**Comment by SunboX** [comment]
👍

**Comment by altima** [comment]
see pull #29

**Comment by SunboX** [comment]
Any news on this? Maybe we can include it in the v1.1.0 release. 😸

**Comment by altima** [comment]
I will try to merge it a second time... ;) there are some changes that interrupt my stuff

**Comment by SunboX** [comment]
Great, I will try to accept the request more quickly. :smirk:

**Comment by altima** [comment]
now, i got it :) see https://github.com/nextcloud/windows-universal/pull/73
