### ISSUE TITLE
Add icons to sort menu flyout entries

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#131]
Looking at the sort menu, I think that the entries contain too much text, e.g. "Size (smallest to the top)".
I would remove the text in brackets because it's clear what the sorting does. As an indicator if the soirting is ascending/descending, I would place an icon in fron of the sort criteria.

So instead of "Size (smallest to the top)" let's use "^ Size".

Any opinions?

**Comment by SunboX** [comment]
I personally would not change it. By now the context menu has the same look&feel like the native File-Explorer app:

![wp_ss_20170429_0003](https://cloud.githubusercontent.com/assets/83344/25554106/a372bfe0-2cc5-11e7-853f-471c74849c18.png)

**Comment by SunboX** [comment]
I do not know, if the asc/desc "arrow" is clear to everyone. For me, as a developer, it's clear. But I think Microsoft had a good reason to do it like this. Don't know, but I would do it like the people are used to.

**Comment by DecaTec** [comment]
OK, we can leave it the way it is.

But what should be the sort description (in brackets) when sorting for data type? Now it's only "(ascending)" or "(descending)"...

**Comment by SunboX** [comment]
The question is, how do you sort by "data type"? By data type name? So it should be the same as sorting by file name (alphabetically).

**Comment by DecaTec** [comment]
OK, I've changed the text when sorting for type: https://github.com/nextcloud/windows-universal/pull/146
We leave the rest as it is.
