### ISSUE TITLE
More understandable repository name

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/windows-universal#14]
»windows-uwp« seems a bit confusing. ;)

Apparently it runs on Windows Phone and also other platforms, hence the naming? But is there a less technical name we can give it?

@SunboX @altima

**Comment by SunboX** [comment]
Hm, it's called "Universal Windows Platform" ... so maybe, "windows-universal" ?

**Comment by jancborchardt** [comment]
That would definitely be better than the acronym! :) If windows-phone or -mobile is too specific, let’s do »windows-universal«.

**Comment by jancborchardt** [comment]
@SunboX @altima renamed it :)

**Comment by SunboX** [comment]
👍
