### ISSUE TITLE
Manual synchronization: When a file got changed locally, it's shown as a conflict

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#149]
- Synchronize a folder to an empty local folder
- First time sync is OK
- Create new file locally
- Synchronize manually
- Change the locally created file
- Synchronize again

**Result:**
A sync conflict is shown by the app (file was created on the server and locally).

**Comment by DecaTec** [comment]
@TheScientist Can you take a look at this?

**Comment by TheScientist** [comment]
Sorry I missed the notification about this bug. Atm I have no time, cause of work and holidays.

**Comment by DecaTec** [comment]
No problem, but we should fix it for release 1.1.0.

**Comment by TheScientist** [comment]
Can't reproduce the error. Can you give me more details about the file (size, type, ??)

**Comment by DecaTec** [comment]
I also can't reprocuce the issue right now. I made some changes regarding DAV URLs a while ago. Maybe the error just went away.
So I'll close this for now.
