### ISSUE TITLE
What is a "share target" 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/windows-universal#152]
One translator pointed out, that "share target" in the app description is not clear.

```
* Share files with the app (share target)
```

What does it mean?

@SunboX

**Comment by SunboX** [comment]
It means, that this app does act as a share target. You can share content from other installed apps (files) with the Nextcloud app. Please see the "Guidelines for sharing content" for more information about that: https://msdn.microsoft.com/en-us/library/windows/apps/hh465251.aspx

**Comment by MorrisJobke** [comment]
It's a quite technical term. Is there a way to properly name this? Or is this really commonly known in the windows phone community? Otherwise I would just drop it. I think many people don't care about those real technical details and may be confused by this. And they will also most likely see if this shows up in the source or target list for shares.

**Comment by SunboX** [comment]
You are right, it doesn't matter much. So I think we can remove it. Do you want to remove it? Otherwiese, I will do it.

**Comment by MorrisJobke** [comment]
> You are right, it doesn't matter much. So I think we can remove it. Do you want to remove it? Otherwiese, I will do it.

Feel free to do it :)
