### ISSUE TITLE
Implement the function to select multiple files and folders

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#16]
multiple file / folder selection for:
* download multiple files to a local folder
* delete multiple folders and files

**Comment by scherke85** [comment]
Hi there, i work on it.
Can you check my first commit

https://github.com/scherke85/windows-universal/commit/64e10518f266a0746672396d7022bd01ae774c7a

next step is when you select a file or folder the AppBarMenu Change and you see delete and download Button

**Comment by SunboX** [comment]
Looks good to me! 👍 

I would also add a commend to move the selected files/folders to another folder.

**Comment by scherke85** [comment]
i merge my branch and add moveToFolder and remove IsSortingToSelectionModeConverter
i think he is superfluous. Can you confirm it?

Next I work on the functionalities.

**Comment by SunboX** [comment]
Looks good to me, would be nice if we can include it in v1.1.0 😄 I will make a deeper code review if you've finished it. But it looks good by now.

**Comment by scherke85** [comment]
hi there,
i have implemented the functionalities to download selected FilesOrFolder

can you check it
https://github.com/scherke85/windows-universal/commits/selectMultipleFilesAndFolders%2316

if this ok i would go on with deleted and then moveToFolder

**Comment by DecaTec** [comment]
What's the current status of this issue?
@scherke85 Maybe you can create a PR when you think the implementation is ready for review. :thumbsup:

**Comment by scherke85** [comment]
I think this issue is solved.

**Comment by DecaTec** [comment]
Yes, it's resolved.
Thanks a lot.
