### ISSUE TITLE
App exit when navigating with the back button

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#160]
Strange behavior when going back with the back button on mobile:
- You have 1 folder with 1 file contained.
- From the main view, navigate to the file detail page for the file mentioned above
- Go back with the (hardware) back button -> you are now in the folder containing the file again -> OK
- Hit the go back button again

Expected behavior: You go back to the main view.
Actual behavior: The app exits.

I've tried to find out the reason for this behavior, but I only found that when hitting the back button for the second time, the handler `DeviceGestureServiceOnGoBackRequested` in App.xaml.cs is called twice. The call stack indicates that both calls to the handler are coming from Prism.

**Comment by SunboX** [comment]
Hm, that's ugly. Just for reference the call stack for `DeviceGestureServiceOnGoBackRequested(object sender, DeviceGestureEventArgs e)`:

## From item detail page to folder page:

```
NextcloudApp.exe
NextcloudApp.App.DeviceGestureServiceOnGoBackRequested(object sender, Prism.Windows.AppModel.DeviceGestureEventArgs e)
Line 434
C#

Prism.Windows.dll
Prism.Windows.AppModel.DeviceGestureService.RaiseCancelableEvent<Prism.Windows.AppModel.DeviceGestureEventArgs>(System.EventHandler<Prism.Windows.AppModel.DeviceGestureEventArgs> eventHandler, object sender, Prism.Windows.AppModel.DeviceGestureEventArgs args)
Unknown

Prism.Windows.dll
Prism.Windows.AppModel.DeviceGestureService.OnHardwareButtonsBackPressed(object sender, Windows.Phone.UI.Input.BackPressedEventArgs e)
Unknown
```

## From folder page to "main" folder page...

### call 1:
```
NextcloudApp.exe
NextcloudApp.App.DeviceGestureServiceOnGoBackRequested(object sender, Prism.Windows.AppModel.DeviceGestureEventArgs e)
Line 434
C#

Prism.Windows.dll
Prism.Windows.AppModel.DeviceGestureService.RaiseCancelableEvent<Prism.Windows.AppModel.DeviceGestureEventArgs>(System.EventHandler<Prism.Windows.AppModel.DeviceGestureEventArgs> eventHandler, object sender, Prism.Windows.AppModel.DeviceGestureEventArgs args)
Unknown

Prism.Windows.dll
Prism.Windows.AppModel.DeviceGestureService.OnHardwareButtonsBackPressed(object sender, Windows.Phone.UI.Input.BackPressedEventArgs e)
Unknown
```

### call 2:
```
NextcloudApp.exe
NextcloudApp.App.DeviceGestureServiceOnGoBackRequested(object sender, Prism.Windows.AppModel.DeviceGestureEventArgs e)
Line 434
C#

Prism.Windows.dll
Prism.Windows.AppModel.DeviceGestureService.RaiseCancelableEvent<Prism.Windows.AppModel.DeviceGestureEventArgs>(System.EventHandler<Prism.Windows.AppModel.DeviceGestureEventArgs> eventHandler, object sender, Prism.Windows.AppModel.DeviceGestureEventArgs args)
Unknown

Prism.Windows.dll
Prism.Windows.AppModel.DeviceGestureService.OnSystemNavigationManagerBackRequested(object sender, Windows.UI.Core.BackRequestedEventArgs e)
Unknown
```

**Comment by SunboX** [comment]
The difference is, that both events are getting fired, [`HardwareButtons.BackPressed`](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/AppModel/DeviceGestureService.cs#L38) and [`SystemNavigationManager.GetForCurrentView().BackRequested`](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/AppModel/DeviceGestureService.cs#L50)

**Comment by SunboX** [comment]
I think the implementation in the Prism library is wrong, it should be similar to this one: https://docs.microsoft.com/en-us/windows/uwp/porting/w8x-to-uwp-porting-to-a-uwp-project#conditional-compilation-and-adaptive-code

**Comment by SunboX** [comment]
I opened an issue for it: https://github.com/PrismLibrary/Prism/issues/1070

**Comment by DecaTec** [comment]
OK, let's see if this got fixed on the other side. 
Otherwise I don't have any clue on how to fix it for the NC app.

**Comment by SunboX** [comment]
I tried to work around it, by doing this:
```c#
private void DeviceGestureServiceOnGoBackRequested(object sender, DeviceGestureEventArgs e)
{
    if (!e.IsHardwareButton)
    {
        e.Handled = true;
        return;
    }
```

but somehow, it doesn't take effekt. 😢

**Comment by DecaTec** [comment]
Any news on this one?

**Comment by SunboX** [comment]
No, not by now. Think we have to fork the PrismLibrary and fix it there. Then use the forked one until the fix has been merged and released by Prism.
