### ISSUE TITLE
Make included libraries universal

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#17]
To make this app a universal app (UWP) we need to fix the included libraries `WebDavClient` and `NextcloudClient`. Both use the `Windows.Web.Http.HttpClient` that is platform dependent. 

I had to use the HttpClient, because Windows Mobile caches the uploading files while it is uploading them. HttpClient accepts a `HttpBaseProtocolFilter` object that has a `CacheControl.WriteBehavior` property you can set to `HttpCacheWriteBehavior.NoCache`.

At first I used `System.Net.WebRequest`, which would be universal available. I tried to get the upload progress like this:

```csharp
var uploadFileRequest = WebRequest.Create(_uri) as HttpWebRequest;
uploadFileRequest.Method = "PUT";
uploadFileRequest.ContentType = _file.ContentType;
uploadFileRequest.Headers["Pragma"] = "no-cache";
uploadFileRequest.Headers["Content-Length"] = stream.Size.ToString();
var stream = await _file.OpenAsync(FileAccessMode.ReadWrite);
using (var inputStream = stream.GetInputStreamAt(0))
{
    using (var dataReader = new Windows.Storage.Streams.DataReader(inputStream))
    {
        const int chunkSize = 256;
        var req = await uploadFileRequest.GetRequestStreamAsync();
        do
        {
            var read = await dataReader.LoadAsync(chunkSize);
            var buffer = new byte[read];
            dataReader.ReadBytes(buffer);
            await req.WriteAsync(buffer, 0, (int)read);
            await req.FlushAsync(); // flushing is required or else we jump to 100% very fast
            BytesSend += (int)read;
        } while (BytesSend < BytesTotal);
        await uploadFileRequest.GetResponseAsync();
        var response = (HttpWebResponse) await uploadFileRequest.GetResponseAsync();
        var result = new HttpResponseMessage(response.StatusCode);
        result.Content = new StreamContent(response.GetResponseStream());
    }
}
```

It will show a progress, but after it reaches 100% it takes more or less the same time to finish. This is because Windows Mobile caches the upload stream while it get's send. So you can only measure the time taken to write this file stream into the send cache of the OS.

Sadly, by now I have not found any way to implement a correct upload progress as windows universal. Maybe someone has an idea how it would work or want's to try out some things?

The only solution I can imagine for now is to implement a file upload method for every platform. But this isn't very nice. 😏

**Comment by DecaTec** [comment]
As already discussed by mail:
On UWP apps there are some problems using System.Net. When making a real UWP app than we should focus on Windows.Web as a base and focus on Windows 10.

I implemented a few additions on my WebDAV library (https://github.com/DecaTec/Portable-WebDAV-Library) and will try to put it to work with the app (maybe next weekend). This way we can pull the WebDAV complexity out of the app itself. That should make things a little easier.

Any further ideas or concerns?

**Comment by SunboX** [comment]
So now only the NextcloudCLient should be made universal and than I think we are mostly done. (except some small UI changes)

Thanks @DecaTec for your great work! ❤️

**Comment by DecaTec** [comment]
I'll have a look at it in the next days.
What are the known problems when running as universal app (I'm always debugging on Win desktop, seems fine so far)?

**Comment by DecaTec** [comment]
I've developed/tested mostly on Win desktop and couldn't find any problems. I think that we can make the app a real UWP app with the next release.

**Comment by SunboX** [comment]
Ok, so I will create two follow-up issues:

* sepparate NextcloudClient Library from the App
* make the App Layout responsible (use more space on bigger screens)

Thanks again for your work! ❤️
