### ISSUE TITLE
Can't load favorites with umlaut

### ISSUE THREAD

**Issue by TheScientist** [nextcloud/windows-universal#193]
An exception is triggered, when I load the favorites page and have an item with an umlaut.
From debugging I saw that the resource item is not filled correctly, an item with all properties unset, so probably a webdav problem.
Displaying the same item in the normal files view works.

**Comment by DecaTec** [comment]
Resolved with https://github.com/nextcloud/windows-universal/commit/f3797e705f178d31da8b9b8e27bf59eea1563d28
