### ISSUE TITLE
Move translation to nextcloud org on transifex

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/windows-universal#22]
Allows existing translators of our project to continue translating throught the complete set of things.

@MorrisJobke

**Comment by MorrisJobke** [comment]
What is the old transifex repo?

**Comment by MorrisJobke** [comment]
@SunboX If you want this, then I can do the migration for you, but I need access to the transifex org to read the existing values. ;)

**Comment by SunboX** [comment]
@MorrisJobke is your nick "kabum" at Transifex? If so, you should now be admin.

**Comment by SunboX** [comment]
Hey @MorrisJobke, could you get access to the Transifex project here? ➡️ https://www.transifex.com/nextcloud-app-uwp/nextcloud-app-uwp/

**Comment by MorrisJobke** [comment]
> Hey @MorrisJobke, could you get access to the Transifex project here? ➡️

I haven't tried yet 😢

**Comment by MorrisJobke** [comment]
Done: https://www.transifex.com/nextcloud/nextcloud/windows-universal/

**Comment by MorrisJobke** [comment]
First push: a88121b9b3256560b08f449d3c03948814c35c3c

Will happen on a daily basis in the future (every night at roughly 3 o'clock)

**Comment by SunboX** [comment]
One more thing, does the bot automatically submit new strings from the english resource file and submit it to Transifex or must I submit them manually?

**Comment by MorrisJobke** [comment]
The bot does everything :)

**Comment by SunboX** [comment]
Oh, nice. :smile: That's a really great thing. Thanks for your work!
