### ISSUE TITLE
Upgrading to 1.1.1 on Lumia 535

### ISSUE THREAD

**Issue by mixedbredie** [nextcloud/windows-universal#254]
I have an issue upgrading to version 1.1.1 on Lumia 535 running OS 10.0.14393.1593.  Nothing I do will upgrade the 1.0.3.0 version I have installed already.  I have uninstalled, rebooted, installed a number of times but it stays at 1.0.3.  What can I do to force the upgrade?  I'd like the auto upload functionality.

The Nextcloud blog has advertised the upgrade to 1.1.0 and 1.1.1 is available in the store but here on Github it still says 1.0.3 is the latest release.  I see the 1.1.0 milestones have been completed.

**Comment by DecaTec** [comment]
v1.1.1 of the app is published to the store (also when not listed in the releases on GitHub).
Usually, the update should work fine, your OS version is the latest one and should meet all requirements.
Have you tried a soft reset of the phone already? If nothing else works, I would try a hard reset (but only if you don't mind starting from scratch with a new installation).

@SunboX Any idea? How many app packages are currently listed for the app in the MS dev center?

**Comment by SunboX** [comment]
> I have an issue upgrading to version 1.1.1 on Lumia 535 running OS 10.0.14393.1593

Hey, the minimum supported OS version is 10.0.15063 now (Creators Update). We have to move forward to be able to use all the fancy new stuff. 

The sad thing is, that Microsoft has not listed the Lumia 535 in their list of devices upgradable to Creators Update. That means you will not be able to receive an official Creators Update from Microsoft.

Maybe you can opt-in to the Windows Insider Programm and receive the Creators Update from there. But I'm not sure.

>  but here on Github it still says 1.0.3 is the latest release. I see the 1.1.0 milestones have been completed.

You are right! I forgot to tag the release here. Thanks for the hint!

**Comment by adilalaa** [comment]
Thanks
