### ISSUE TITLE
still don't receive the upgrade to version 1.1.1, on windows 10 mobile "anniversary update"

### ISSUE THREAD

**Issue by sviluppoSoftware** [nextcloud/windows-universal#257]
now i have the 1.0.3 version someone can tell me if has the same problem please?  i had think that was a MIcrosoft Store problem, so i used this guide: https://support.microsoft.com/en-us/help/13390/lumia-what-to-do-if-i-cannot-download-or-update-apps-from-store
but doesn't fix, other apps i have installed receive regular update without any problem, i also trying to hard reset the smartphone.

**Comment by DecaTec** [comment]
For the latest version of the app, you'll need Windows 10 Mobile Creators Update.
Please take a look here for more information: https://github.com/nextcloud/windows-universal/issues/254
