### ISSUE TITLE
ETag in file details

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#39]
Why is the ETag shown in the details of a file? Imho that's not an info the user cares about.

Shouldn't it be removed?

**Comment by SunboX** [comment]
Why not? I would give all information to the user we have. It's not really relevant for me or you, but maybe for someone else that wants to debug it's WebDav API. I don't know, but as long as it didn't hurt... why not?

**Comment by ocdtrekkie** [comment]
This may be useful to me, as I'm hoping to work on figuring out compatibility between this client and a piece of software that generally works with ownCloud clients.

**Comment by SunboX** [comment]
Will wait for more people to comment on this. Should we leave the feature implemented or are there any reasons to remove it? Is it confusing to a "normal" user, or doesn't it matter at all?

**Comment by DecaTec** [comment]
Usually you use the ETag to dertermine if a resource has changed ("lost update" problem). So this is a technical property and has no use for the end user.

Should be only interesting for developers.

**Comment by SunboX** [comment]
Maybe we should introduce some kind of "developer" setting. So dev's are able to see all details and we do not confuse normal users?

**Comment by DecaTec** [comment]
When the ETag field should stay on the detail page, we should put it at the end of the list, because it's the least relevant detail (for the user).

**Comment by DecaTec** [comment]
See https://github.com/nextcloud/windows-universal/pull/124

Moved ETag at the end of the list of a file's details as it's the least important information.

Imho this info is absolutely not interesting for the default user and we should entirely remove it...I'll leave this issue open.

Ceterum censeo Carthaginem esse delendam 😁

**Comment by SunboX** [comment]
So no more comments since five months now. Let's introduce a "developer mode" setting and hide the ETag if the dev mode is turned off. Should be off by default.

I'm sure we will need this dev mode some more times.

**Comment by DecaTec** [comment]
Resolved by https://github.com/nextcloud/windows-universal/pull/132

**Comment by DecaTec** [comment]
Renamed 'developer mode' to 'expert mode': https://github.com/nextcloud/windows-universal/pull/135

I think that in the future, we maybe have some settings/app features which are not only useful if you are a developer, but also when you're an 'expert user'.
