### ISSUE TITLE
User authentication on app start

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#44]
Other apps like OneDrive have a feature that the user has to authenticate by pin/Windows Hello at app start. Makes sense because the app shows personal data.

Maybe it's a good idea to implement such a feature. The user may switch authentication on/off in the settings.

**Comment by SunboX** [comment]
Good point, I thought about that, too. Windows Hello is the right thing for that!

We should ask the user after the initial log in, if he wants to use Windows Hello to secure the app. ALso there should be a option in the settings to enable/disable Windows Hello.

**Comment by SunboX** [comment]
Just as a side note, another option can be, to only use Windows Hello if the user starts a file download.

**Comment by DecaTec** [comment]
Windows Hello takes some time to identify user. From a user's perspective it slows down working with the app when downloading a single file.
The main reason for authentication should be the presence of personal data. That is given when the app is running and before a file gets downloaded (just think about thumbnails).

Imho authentication is only useful at app start.

**Comment by SunboX** [comment]
K, makes sense. Only on app start then. 😏

**Comment by SunboX** [comment]
implemented with https://github.com/nextcloud/windows-universal/pull/55
