### ISSUE TITLE
Wrong group header when sorting for size

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#48]
When items are grouped by size (asc or desc), the group header will always be 'B'.

We shouldn't use group headers here or use group headers with size ranges (<1MB, <10MB, etc.).

**Comment by DecaTec** [comment]
By looking at the source the 'B' is for 'Bytes'.
However, I think that this is not very user friendly.

**Comment by SunboX** [comment]
Let me think of this a bit more. Generally I'm with you. I can remember that I thought a long time about how to present this to the user.

Another solution can be to remove the grouping header completely in this case. I have to think about it.

**Comment by DecaTec** [comment]
Resolved: https://github.com/nextcloud/windows-universal/commit/0c782ff02fc91626209ab35317e8c450215d32be
