### ISSUE TITLE
Clear PasswordVault when resetting the app

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/windows-universal#50]
After app reset you can log in with any password as long as server URl and user name are the same as before the reset.

When resetting the app we should call PasswordVault.Remove.

**Comment by DecaTec** [comment]
I've seen that this is already done in the SettingsPageViewModel. I wouldn't expect it here, think this should happen in the settings class.
The problem I ran into was that after resetting, there is only a navigation to the login page. Here you can actually insert any password and are redirected to the folder overview.

So maybe it's a good idea to terminate the app after the reset (maybe with a message box telling the user that the app will close).

**Comment by SunboX** [comment]
> So maybe it's a good idea to terminate the app after the reset (maybe with a message box telling the user that the app will close).

No, from a user view this is a terrible behavior. Like "you must restart your PC to finish the update". 😏 
I will look into this as soon as I'm getting the time to.

But a good catch! Thanks for the report! ❤️

**Comment by DecaTec** [comment]
Maybe also a good idea to put the vault.Retrieve in a try-catch block. I had some problems while debugging. When no credentials are available, vault.Retrieve will throw an exception which prevents to following up code to be executed.

**Comment by DecaTec** [comment]
While working on #55, I've tracked the real problem:
When the app gets reset, the user is redirected to the login page. Entering invalid credentials, the HEAD request checking the user credentials (method CheckUserLogin), will return true due to an HTTP 200 (OK) response message.
I don't have an explanation for this behavior. Even trying not to cache any data will lead to the same result.

As a possible fix in #55, I've changed the CheckUserLogin method, so we're doing an API call for the user attributes. This will always fail when the invalid credentials are specified.

**Comment by altima** [comment]
IS the PasswordVault working? I got errors while using the last commits on the retrive function?! I already added try catch to prevent it, but the combase.dll from the device throws unexpected error... 

I'm using the emulator 10.0.10586, any ideas?

**Comment by DecaTec** [comment]
No problems on 10.0.10586 (with pull request #55).
What's the exact location where you're getting problems?

**Comment by altima** [comment]
I got this problem direct after login.

**Comment by altima** [comment]
UPDATE: there is a maybe problem in the PasswordVault with mail addresses as username.

**Comment by SunboX** [comment]
PasswordVault retrieve will fail, if there's a dot `"."` in the username filed. I will investigate this further.

**Comment by SunboX** [comment]
I can't find the root cause for this bug. But I have an idea how to change the implementation a bit, so that I can work around this.

Basically, I will retrieve all credentials for a domain and iterate over them to find the one with the right username. Should work like this.

**Comment by SunboX** [comment]
@altima should work now. Was fixed with https://github.com/nextcloud/windows-universal/pull/64
