### ISSUE TITLE
Error after login "Invalid query, please check the syntax."

### ISSUE THREAD

**Issue by togglecode** [nextcloud/windows-universal#53]
I'm getting this error from the app after I login in the application:
"Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:"

The steps to reproduce it:
1. login into the app
2. close the app
3. Open the app again and you get the error

I'm not a developer, but I just leave my prediction here (maybe it saves you time). The reason for the error seems to be because of GetUserAttributes method in NextCloudClient.cs, for some reason the App is sending a GET request to https://demo.nextcloud.com/ocs/v1.php/cloud/users/Test which returns this error.

```
 public async Task<User> GetUserAttributes(string username)
        {
            var response = await DoApiRequest(
                "GET",
                "/" + GetOcsPath(OcsServiceCloud, "users") + "/" + username
                );

            var responseStr = response;

            return GetUser(responseStr);
        }
```

App version: Nexcloud App from master branch commit 37cbc702f3d249911906f1f3cbf785896d7fc0e1
Server: demo.nexcloud.com

Screenshot of error:
![wp_ss_20161130_0002 1](https://cloud.githubusercontent.com/assets/17141698/20753329/2a4d2356-b706-11e6-8c4c-719df55a3679.png)

**Comment by DecaTec** [comment]
Seems like method GetUserAttributes is called with null as parameter which results on an invalid API request.

Working on it...
