### ISSUE TITLE
Investigate, SSL server connection with self signed certificates

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#57]
Investigate, if there's a way to connect (HTTPS) to a server that is setup with a self signed SSL certificate.

## current behavior
By now, the app will show a message that the server is unreachable.

## if allowing self signed certificates is not possible
If there is now way to allow self signed certificates, the app should show a more clear message, like

> This server is using a self signed certificate. Sadly we can not connect to it.

## user story
https://help.nextcloud.com/t/server-not-found-from-windows-10-mobile-app/6669

**Comment by SunboX** [comment]
Maybe, this setting will do it:
https://msdn.microsoft.com/en-us/library/windows/apps/windows.web.http.filters.httpbaseprotocolfilter.ignorableservercertificateerrors.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1

**Comment by DecaTec** [comment]
See https://github.com/DecaTec/Portable-WebDAV-Library/wiki/Untrusted-or-expired-SSL-certificates

**Comment by MariusBluem** [comment]
Great to see, that this is fixed that fast 💪 
Hmm ... Shouldn't we show a checkbox for that 😁 (Connect **even if** ...) @SunboX

**Comment by SunboX** [comment]
I thought about that too, but didn't want to introduce to much config at app start. Maybe we could show a message box in case of unsecure certificates. I will create a separate issue for that. :smirk:

**Comment by MariusBluem** [comment]
Problem now is... that the Client is going to trust simply every server with a certificate (even if the certificate is not valid) and this is not shown to the user ... This opens possibilities for MITM-attacks 😅 (...IMHO with my small security knowledge) 

What do you think? @LukasReschke

**Comment by SunboX** [comment]
> Problem now is... that the Client is going to trust simply every server with a certificate (even if the certificate is not valid) and this is not shown to the user ... This opens possibilities for MITM-attacks

I know. See my comment here. ;) https://github.com/nextcloud/windows-universal/pull/60

**Comment by DecaTec** [comment]
We should try to login as usual. If that fails, then we should add a check box ("connect even if...") to the login screen and the user has to try again.

I wouldn't force the user to use a valid cert - before Let's Encrypt, self signed certs were quite popular imho.

**Comment by SunboX** [comment]
Can someone please provide me a Nextcloud server instance / user account that runs a self signed certificate? 🍺

**Comment by MariusBluem** [comment]
> Can someone please provide me a Nextcloud server instance / user account that runs a self signed certificate? 🍺

I've sent you a message in the forum 👊

**Comment by SunboX** [comment]
Hey, that's great. Let's see if I get some time the next days. I will let you know! :+1:

**Comment by captainjoh** [comment]
Still or again not working for me
