### ISSUE TITLE
Replace Behaviors SDK (XAML) version 12.0 with Behaviors.UWP

### ISSUE THREAD

**Issue by revan1199** [nextcloud/windows-universal#58]
Behaviors SDK should be replaced with UWP SDK (Microsoft.Xaml.Behaviors.Uwp.Managed):
https://blogs.windows.com/buildingapps/2015/11/30/xaml-behaviors-open-source-and-on-uwp/

**Comment by SunboX** [comment]
good point, fixed with https://github.com/nextcloud/windows-universal/pull/59
