### ISSUE TITLE
Implement the function for managing shares

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#6]
This (more or less) depends on issue #5 

**Hambrger menu**
* All files
* Shared with you
* Shared with others
* Shared by link

**Comment by HiveSolution** [comment]
Hey,
I'm currently taking a look at this issue.
I tried to reverse my way through the code to find the point where the ViewModel gets what it has to pull.

Maybe I'm on a completely wrong path here, but isn't it the ViewModel that has to know what data has to be fetched?

Would be awesome if you could point me in the right direction, so i can add those different views.

**Comment by TheScientist** [comment]
As Prism as MVVM Framework is used, all public fields and commands can be data bound to the ui.
So for example in the Views/DirectoryListPage.xaml the grouped file list is bound to `Directory.GroupedFilesAndFolders` (line 20)
In the ViewModel (ViewModels/DirectoryListPageViewModel.cs) you'll find a public property Directory which returns an instance of DirectoryService.cs which itself again has the property GroupedFilesAndFolders `public ObservableCollection<Grouping<string, FileOrFolder>> GroupedFilesAndFolders => _groupedFilesAndFolders.Items;(
blic ObservableCollection<Grouping<string, FileOrFolder>> GroupedFilesAndFolders => _groupedFilesAndFolders.Items;`(line 51)

**Comment by HiveSolution** [comment]
As of my last post I have been working on shares and favorites viewing.

My fork is currently able to view `Shares with others`. 

I'm now working on viewing my favorites. Trying to do so using the `filter-rules` on dav requests.
When attempting to do so, using `SendRequestAsync` this is the response i get:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
	<s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
	<s:message>Listing members of this collection is disabled</s:message>
</d:error>
```

Any Ideas why I'm getting this? My request path is this: `/remote.php/dav/files`

Also, feel free to check out my fork of you'd like to take a closer look at the problem. If you try to test this using my fork just exchange the if case in `DirectoryService.cs` to use the `sharesOut` check, since the favorites view is not implemented yet, since i'm just testing out methods to get the favorites.

**Comment by HiveSolution** [comment]
@SunboX Did you, by any chance, find the time to look into this?

**Comment by SunboX** [comment]
Hey @HiveSolution, no, not by now. We are currently working on the Release of Version 1.1

Can you intercept the network traffic of another Nextcloud app (iOS or Android) to get a clue about what's wrong? I personally prefer Telerik Fiddler for network traffic sniffing, but Charles Proxy works also very well.

If I get some time, I will take a look at it. But by now I have not much spare time left. Maybe @TheScientist has some time to take a look?

**Comment by TheScientist** [comment]
@HiveSolution Sorry I'm no expert in webdav stuff. Looks like a setting (in nextcloud??) does not permit to read favorites.

**Comment by HiveSolution** [comment]
What I've looked into so far, is the Request made by Nextcloud itself.

When clicking on favorites it creates a request of the type `REPORT` to `/remote.php/webdav/`.

Also attaching a XML Payload:

```
<oc:filter-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
    <d:prop>
        <d:getlastmodified />
        <d:getetag />
        <d:getcontenttype />
        <d:resourcetype />
        <oc:fileid />
        <oc:permissions />
        <oc:size />
        <d:getcontentlength />
        <nc:has-preview />
        <oc:tags />
        <oc:favorite />
        <oc:comments-unread />
        <oc:owner-display-name />
        <oc:share-types />
    </d:prop>
    <oc:filter-rules>
        <oc:favorite>1</oc:favorite>
    </oc:filter-rules>
</oc:filter-files>
```

Grabbing this request and using it inside `Postman` I get my Favorites as `XMLHttpResponse`, wierd thing is that i always get my favorites and one empty propstat with `<d:status>HTTP/1.1 404 Not Found</d:status>`, but it's still working, so I'm guessing this is just what's supposed to happen. (Maybe a file that was in my favorites but got removed?)

Doing the same request from the App, I get the above mentioned error.

I still have to test the Android App and check its traffic and apply this to the code.

**Comment by DecaTec** [comment]
> When clicking on favorites it creates a request of the type `REPORT` to `/remote.php/webdav/`.

What do you mean by "request of type `REPORT`"? Kind of `new HttpMethod("REPORT")`?
The headers sent by this requests may also be interesting (and necessary).

Maybe it's a good idea creating a PR (even when the favorites do not work yet)?

btw: Looking at the propfind response content, there are some properties from the namespace `oc` and `nc`. In general, a documentation of the DAV extensions would be a great thing to have.

**Comment by HiveSolution** [comment]
This is my current Request:

`var request = new HttpRequestMessage(new HttpMethod("REPORT"), url.ToUri());`

url being: `var url = new UrlBuilder(_url + "/remote.php/dav/files");` (also tested with `/remote.php/webdav`).

I then attach the payload to the Request: 

`new HttpStringContent(content, Windows.Storage.Streams.UnicodeEncoding.Utf8, "application/xml");`

Content is the above mentioned XML Payload.

I've also tried the `PROPFIND` method, that is mentioned in the documentation. This is also the active Method in my fork. (https://github.com/HiveSolution/windows-universal/blob/shares/NextcloudClient/NextcloudClient.cs#L283)

**Comment by HiveSolution** [comment]
UPDATE:

The problem appeared to be the URI from the documentation and mixing up props on my end.

Using the URI `remote.php/webdav` and the correct properties I got my favorites as XML Response.

----

Will be implementing it later this week and create a PR, allowing us to view sharing out and favorites.

**Comment by DecaTec** [comment]
Just as a reminder: You can find a list of all NC WebDAV properties here: https://docs.nextcloud.com/server/12/developer_manual/client_apis/WebDAV/index.html

**Comment by HiveSolution** [comment]
Favorites are now working in my Fork, here's a little overview/todo on whats done, and still needs to be done.

- [ ] Shared with you (Currently working on this)
- [x] Shared with others (Done and containing shared by link
- [ ] Shared by link (Up next, after sharing with you)
- [x] Favorites (Done)

--------

PR will be either created after those 2 missing features are added, or ASAP if you wish so.

--------

Thanks again to all of you for the help!

**Comment by DecaTec** [comment]
Merged with https://github.com/nextcloud/windows-universal/pull/150
