### ISSUE TITLE
Implement the function to download directories as zip file

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#7]

**Comment by scherke85** [comment]
I assume this issue - I'll try it
can you help me structure the files

**Comment by SunboX** [comment]
Hey, that's great! 👍 I will try to get you started.

I have already (blindly) implemented the "raw" function to download a remote directory as zip file. You can find it in the `NextcloudClient/NextcloudClient.cs` here https://github.com/nextcloud/windows-universal/blob/master/NextcloudClient/NextcloudClient.cs#L305
But I did not try if it works by now! So be aware that this function might not actual work. 😏 
If you like, you can change the methods signature and response, that's no issue.

The "entry point" for starting a directory download (as zip) should be the context menu of a directory entry (long press on directory name). It should be name something like "Download as zip file".

You define the context entries here: https://github.com/nextcloud/windows-universal/blob/master/NextcloudApp/Views/DirectoryListPage.xaml#L245

Then you should create a new View and a belonging ViewModel. I would name the View `DirectoryAsZipDownloadPage.xaml` and the ViewModel `DirectoryAsZipDownloadPageViewModel.cs`.
Both should more or less behave the same like the `SingleFileDownloadPage` and it's ViewModel.

All required strings should be defined in the Resources file here: https://github.com/nextcloud/windows-universal/blob/master/NextcloudApp/Strings/en-US/Resources.resw (so they are translatable)

If you need any help, let me know! :metal:

**Comment by scherke85** [comment]
Evening, the text "Download as ZIP file" is also displayed in a single file - do you know how can you intercept? Then text "Download" should be used.

**Comment by SunboX** [comment]
Oh, thanks for the hint! Basically you have to use two Context entries and change the visibility by type using a Converter. I will fix it. :)

**Comment by SunboX** [comment]
fixed with dca28de91f9f4892361abbbb273818cfcd7e590c
