### ISSUE TITLE
Unable to upload larger files.

### ISSUE THREAD

**Issue by LidhemRV** [nextcloud/windows-universal#82]
When uploading pictures from my phone the normal pictures of around 4-6 MB work fine, but a short movie (260 MB) stops uploading at around 18 MB, there is no error message, the progress just stops.

Using nextcloud server 11.0.2

**Comment by SunboX** [comment]
Hey, thanks for the bug report!

What happens if you try to upload this file using a desktop client or the web interface? For me, it sounds like the server is closing the connection after some time. But you are right, the client has to show a message about whats going on here.

**Comment by LidhemRV** [comment]
Hi, the desktop client (OSX version 2.2.4, build 1) works fine including larger files. I have just tested the web-interface (normally only use the sync client) with a 63 mb file (max file size in PHP is 128 MB), and this uploaded without a problem (bit slow about 4 minutes).

I tried to change the max-file size and other PHP settings in my webserver, but the behaviour stayed the same, the sync client just stops.

On a side note, background sync would in my view be the no.1 priority in a new version (just my 2 cents). Great that you take the time to develop a Windows phone app! I am unfortunately not a developer myself, but I am happy to test. 

Kind regards,

René Verschoor.

**Comment by SunboX** [comment]
> Hi, the desktop client (OSX version 2.2.4, build 1) works fine including larger files. I have just tested the web-interface (normally only use the sync client) with a 63 mb file (max file size in PHP is 128 MB), and this uploaded without a problem (bit slow about 4 minutes).
> 
> I tried to change the max-file size and other PHP settings in my webserver, but the behaviour stayed the same, the sync client just stops.

Ok, I will take a look into it.

> On a side note, background sync would in my view be the no.1 priority in a new version (just my 2 cents). Great that you take the time to develop a Windows phone app! I am unfortunately not a developer myself, but I am happy to test.

There's already someone working on it. 😄 The next version will have manual triggered synchronisation, that's the first step. Background sync will be in one of the next versions (it's not that easy).

https://github.com/nextcloud/windows-universal/issues/10#issuecomment-285942635

**Comment by DecaTec** [comment]
Got it!

As using `HttpClient` internally, it has a default timeout of 100 seconds (see [MSDN](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout(v=vs.110).aspx)). 
When uploading larger files, it runs into that timeout and the task gets cancelled by the runtime.

A possible solution would be to set an infinite timeout. Imho this should be OK here. Any opinions?

However, I'll add a timeout property to `WebDavSession`, as other people may also run into that issue.
